plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"

importOrderSeparation: true
importOrder:
  - "^dotenv/(.*)$"
  - "^react$"
  - "^next"
  - "^node:"
  - "<THIRD_PARTY_MODULES>"
  - "^@/(.*)$"
  - "^[./]"
