plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-tailwindcss"

tailwindFunctions:
  - "cva"
  - "tv"
  - "twMerge"
  - "clsx"
  - "cn"

importOrderSeparation: true
importOrder:
  - "^dotenv/(.*)$"
  - "^react$"
  - "^next"
  - "^node:"
  - "<THIRD_PARTY_MODULES>"
  - "^@/(.*)$"
  - "^[./]"
